### ISSUE TITLE
Add per year pricing

### ISSUE THREAD

**Issue by FGRibreau** [image-charts/website#1]
Like in Redsmin, add a toggle to move between yearly and monthly plans:
<img width="1047" alt="Screenshot 2019-05-12 18 03 58" src="https://user-images.githubusercontent.com/138050/57584839-58091f80-74e0-11e9-9a7c-c4774f68f165.png">

- Enterprise yearly plan is at €529.00 EUR / year
- unlike the monthly subscription, the plan id is `enterprise-yearly-2016` thus the button link target should be `https://image-charts.com/enterprise/customers?plan_id=enterprise-yearly-2016`
- Yearly plans must be displayed by default

1/ Create branch / work / commit
2/ Push branch to github / create PR from your branch to master
3/ Ask me to review

Don't use jQuery or other stuff, do it in plain javascript. (read http://youmightnotneedjquery.com/ )

```js
const plans = [{
id: 'enterprise-2016'
price: '49.00',
currency: '€'
interval: 'monthly'
},{
id: 'enterprise-yearly-2016'
price: '529.00',
currency: '€',
interval: 'yearly'
}];
```

**Comment by AugustinRibreau** [comment]
Info to subscribe in the printing area of the site. For the Toggle, save 10%. 2 buttons for year-to-month switch.
Enterprise button redirect not to the last URL but to https://image-charts.com/enterprise/customers?plan_id=enterprise-yearly-2016 .
